// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZenitelConnectProOperator.Data.Db;

#nullable disable

namespace ZenitelConnectProOperator.Migrations.OperationDb
{
    [DbContext(typeof(OperationDbContext))]
    partial class OperationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("ConnectPro.Configuration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControllerName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisplayConfigurationInSmartClient")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnablePopupWindow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorLogFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorDirNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorMachineName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Port")
                        .HasColumnType("TEXT");

                    b.Property<string>("Realm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerAddr")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("MachineName")
                        .IsUnique();

                    b.HasIndex("OperatorMachineName");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("ConnectPro.Models.Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FQID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Camera");
                });

            modelBuilder.Entity("ConnectPro.Models.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CallState")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeviceState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerIP")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("device_ip")
                        .HasColumnType("TEXT");

                    b.Property<string>("device_type")
                        .HasColumnType("TEXT");

                    b.Property<string>("dirno")
                        .HasColumnType("TEXT");

                    b.Property<string>("location")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId");

                    b.HasIndex("device_ip");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("ConnectPro.Models.DeviceCamera", b =>
                {
                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CameraId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeviceId", "CameraId");

                    b.HasIndex("CameraId");

                    b.ToTable("DeviceCamera");
                });

            modelBuilder.Entity("ConnectPro.Models.Operator", b =>
                {
                    b.Property<string>("MachineName")
                        .HasColumnType("TEXT");

                    b.HasKey("MachineName");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("ConnectPro.Configuration", b =>
                {
                    b.HasOne("ConnectPro.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorMachineName")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("ConnectPro.Models.DeviceCamera", b =>
                {
                    b.HasOne("ConnectPro.Models.Camera", "Camera")
                        .WithMany("DeviceCameras")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConnectPro.Models.Device", "Device")
                        .WithMany("DeviceCameras")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ConnectPro.Models.Camera", b =>
                {
                    b.Navigation("DeviceCameras");
                });

            modelBuilder.Entity("ConnectPro.Models.Device", b =>
                {
                    b.Navigation("DeviceCameras");
                });
#pragma warning restore 612, 618
        }
    }
}
